### ISSUE TITLE
Inconsistent page layout for device, explanatory, and repair guide pages!!

### ISSUE THREAD

**Issue by ASRepairs** [repair-wiki/wiki-issues#10]
![example1](https://github.com/repair-wiki/wiki-issues/assets/142666435/378f39e5-cd50-408e-929c-16b88cc5f30d)
![example2](https://github.com/repair-wiki/wiki-issues/assets/142666435/c64d8f37-262c-4dc3-b0be-abde133eb414)
![example3](https://github.com/repair-wiki/wiki-issues/assets/142666435/35a7d6d8-7b9d-4e67-a0cc-3b7347347e99)

**Comment by untocodes** [comment]
This appears to be due to the tools not fitting along the title in cases where the title is longer.

That's the expected behavior in this case.
